#This code was written for the analysis of GMP cell lifetime data as described in CR paper:
#'Quantifying intrinsic and extrinsic control of cell fates in cancer and stem/progenitor cell pedigrees with competing risks analysis'
#Code was written by R.E. Nordon and J.A. Cornwell 
#For questions please email: r.nordon@unsw.edu.au or james_cornwell@outlook.com

#The data is drawn from these files: 'GMPDivisionCrossOdds.txt'
#                                    'GMPCrossOdds.txt'
#                                    'GMPRegression.txt'


#dependent libraries
library(R.matlab) #R.matlab version 3.1.1 used
library(timereg) #timereg version 1.7.0 used
library(mets) #mets version 0.1-13 used
library(cmprsk) #cmprisk version 2.2-7 used
library(survival) #survival version 2.37-7 used
#dependant files
source("F:/James/R/ProbandwisePlot.R")
source("F:/James/R/addSisterClusterID.R")
source("F:/James/R/PlotPairedData.R")
source("F:/James/R/ClusterMothersAndDaughters.R")
source("F:/James/R/getMothersGFPStatus.R")
source("F:/James/R/getMothers.R")
source("F:/James/R/getCompletePairs.R")
source("F:/James/R/SampleClones.R")
source('F:/James/R/getpairs.R')
source('F:/James/R/getMotherAndDaughterpairs.R')
source('F:/James/R/ResetClustering.R')

## Importing data from Matlab ##
# This file is generated by CrossOdds4Division_script.m
FileName<-"F:/James/R/Analysis in R/GMPDivisionCrossOdds.txt"
data<-read.table(FileName)
# Probandwise Concordance for Mitosis for sisters and regress distance between sisters  ------------------------
is.sisterpair<-data$Relatedness==1
sisters<-data[is.sisterpair,]

#    Include GFP status in competing risks analysis

#  # Cause: None=0(right-censored), Division, Apoptosis, Lost
# Growth_Factor= 1(G-CSF),2(M-CSF)

# New definition of risks are
#  None=0 (right censored), Division (GFP-)=1, Apoptosis (GFP-)=2, Lost (GFP-)=3
#  Division (GFP+)=4, Apoptosis (GFP+)=5, Lost (GFP+)=6
# 
Status<-sisters$GFP*3+sisters$Cause
Status[(sisters$Cause==0)&(sisters$GFP)]<-0
sisters$Status<-Status

# export MothersAndDaughters to excel for review
write.table(sisters,"H:\\CellRxLabDoc\\Papers\\My draft papers\\Competing Risks\\James version\\GMP\\sisters.txt",sep="\t")


# Cause: None=0(right-censored), Division, Apoptosis, Lost
# Growth_Factor= 1(G-CSF),2(M-CSF)


# G-CSF 
times=seq(0.01,3,by=0.02)
ind<-(sisters$Growth_Factor==1)
tempdata<-sisters[ind,]

cif.model.sisters.GCSF.division.GFPn<-comp.risk(Surv(Event_Time,Cause>0) ~ cluster(PairID),
                      data=tempdata,cause=tempdata$Status,
                      causeS=1,resample.iid=1,model="additive",max.clust=10000)
cor.sisters.GCSF.division.GFPn<-cor.cif(cif.model.sisters.GCSF.division.GFPn,sym=1,
                                                    data=tempdata,cause1=1,cause2=1)
summary(cor.sisters.GCSF.division.GFPn)

# regress distance between twins
times=seq(0.1,3,by=0.01)
theta.des<-model.matrix(~1+sqrt(tempdata$Diffusion_distance))
cor.sisters.GCSF.division.GFPn.distance<-cor.cif(cif.model.sisters.GCSF.division.GFPn,
                                        data=tempdata,cause1=1,cause2=1,
                                        theta.des=theta.des,silent=0)
summary(cor.sisters.GCSF.division.GFPn.distance)
rr.sisters.GCSF.division.GFPn.distance<-rr.cif(cif.model.sisters.GCSF.division.GFPn,
                                                 data=tempdata,cause1=1,cause2=1,
                                                 theta.des=theta.des,silent=0)
summary(rr.sisters.GCSF.division.GFPn.distance)


ind<-(sisters$Growth_Factor==1)
tempdata<-sisters[ind,]
cif.model.sisters.GCSF.division.GFPp<-comp.risk(Surv(Event_Time,Cause>0) ~ cluster(PairID),
                                                data=tempdata,cause=tempdata$Status,
                                                causeS=4,resample.iid=1,model="additive",max.clust=10000)
cor.sisters.GCSF.division.GFPp<-cor.cif(cif.model.sisters.GCSF.division.GFPp,
                                        data=tempdata,cause1=4,cause2=4)
summary(cor.sisters.GCSF.division.GFPp)

# regress distance between twins
theta.des<-model.matrix(~1+sqrt(tempdata$Diffusion_distance))
cor.sisters.GCSF.division.GFPp.distance<-cor.cif(cif.model.sisters.GCSF.division.GFPp,
                                                 data=tempdata,cause1=4,cause2=4,
                                                 theta.des=theta.des)
summary(cor.sisters.GCSF.division.GFPp.distance)
rr.sisters.GCSF.division.GFPp.distance<-rr.cif(cif.model.sisters.GCSF.division.GFPp,
                                               data=tempdata,cause1=4,cause2=4,
                                               theta.des=theta.des)
summary(rr.sisters.GCSF.division.GFPp.distance)




# M-CSF

ind<-(sisters$Growth_Factor==2)
tempdata<-sisters[ind,]
cif.model.sisters.MCSF.division.GFPn<-comp.risk(Surv(Event_Time,Cause>0) ~ cluster(PairID),
                                                data=tempdata,cause=tempdata$Status,
                                                causeS=1,resample.iid=1,model="additive",max.clust=10000)
cor.sisters.MCSF.division.GFPn<-cor.cif(cif.model.sisters.MCSF.division.GFPn,
                                        data=tempdata,cause1=1,cause2=1)
summary(cor.sisters.MCSF.division.GFPn)

# regress distance between twins
theta.des<-model.matrix(~1+sqrt(tempdata$Diffusion_distance))

cor.sisters.MCSF.division.GFPn.distance<-cor.cif(cif.model.sisters.MCSF.division.GFPn,
                                        data=tempdata,cause1=1,cause2=1,
                                        theta.des=theta.des)
summary(cor.sisters.MCSF.division.GFPn.distance)

rr.sisters.MCSF.division.GFPn.distance<-rr.cif(cif.model.sisters.MCSF.division.GFPn,
                                                 data=tempdata,cause1=1,cause2=1,
                                                 theta.des=theta.des)
summary(rr.sisters.MCSF.division.GFPn.distance)


ind<-(sisters$Growth_Factor==2)
tempdata<-sisters[ind,]
cif.model.sisters.MCSF.division.GFPp<-comp.risk(Surv(Event_Time,Cause>0) ~ cluster(PairID),
                                                data=tempdata,cause=tempdata$Status,
                                                causeS=4,resample.iid=1,model="additive",max.clust=10000)
cor.sisters.MCSF.division.GFPp<-cor.cif(cif.model.sisters.MCSF.division.GFPp,
                                        data=tempdata,cause1=4,cause2=4)
summary(cor.sisters.MCSF.division.GFPp)

# regress distance between twins
# didn't converge
theta.des<-model.matrix(~1+sqrt(tempdata$Diffusion_distance))
cor.sisters.MCSF.division.GFPp.distance<-cor.cif(cif.model.sisters.MCSF.division.GFPp,
                                        data=tempdata,cause1=4,cause2=4,theta.des=theta.des)
summary(cor.sisters.MCSF.division.GFPp.distance)


rr.sisters.MCSF.division.GFPp.distance<-rr.cif(cif.model.sisters.MCSF.division.GFPp,
                                        data=tempdata,cause1=4,cause2=4,theta.des=theta.des)
summary(rr.sisters.MCSF.division.GFPp.distance)
# plot division concordance for daughters ------------------------------------------
par(mfcol=c(2,2))
par(mar=c(5,5,4,2)+0.1)
marg.cif1<-predict(cif.model.sisters.GCSF.division.GFPn,X=1)
ProbandwisePlot(cor.sisters.GCSF.division.GFPn,marg.cif1=marg.cif1,
                marg.cif2=marg.cif1,title="GCSF GFP- division age",eventtxt1="Sib1",eventtxt2="Sib2")
marg.cif1<-predict(cif.model.sisters.GCSF.division.GFPp,X=1)
ProbandwisePlot(cor.sisters.GCSF.division.GFPp,marg.cif1=marg.cif1,
               marg.cif2=marg.cif1,title="GCSF GFP+ division age",eventtxt1="Sib1",eventtxt2="Sib2")
marg.cif1<-predict(cif.model.sisters.MCSF.division.GFPn,X=1)
ProbandwisePlot(cor.sisters.MCSF.division.GFPn,marg.cif1=marg.cif1,
                marg.cif2=marg.cif1,title="MCSF GFP- division age",eventtxt1="Sib1",eventtxt2="Sib2")
marg.cif1<-predict(cif.model.sisters.MCSF.division.GFPp,X=1)
ProbandwisePlot(cor.sisters.MCSF.division.GFPp,marg.cif1=marg.cif1,
                marg.cif2=marg.cif1,title="MCSF GFP- division age",eventtxt1="Sib1",eventtxt2="Sib2")
# Probandwise Concordance for Apoptosis for Sisters and regress distance apart -----------------------
# G-CSF 
times=seq(0.01,3,by=0.02)
ind<-(sisters$Growth_Factor==1)
tempdata<-sisters[ind,]
cif.model.sisters.GCSF.apoptosis.GFPn<-comp.risk(Surv(Event_Time,Cause>0) ~ cluster(PairID),
                                                data=tempdata,cause=tempdata$Status,
                                                causeS=2,resample.iid=1,model="additive",max.clust=10000)
cor.sisters.GCSF.apoptosis.GFPn<-cor.cif(cif.model.sisters.GCSF.apoptosis.GFPn,
                                        data=tempdata,cause1=2,cause2=2)
summary(cor.sisters.GCSF.apoptosis.GFPn)

#regress distance appart

theta.des<-model.matrix(~1+sqrt(tempdata$Diffusion_distance))
cor.sisters.GCSF.apoptosis.GFPn.distance<-cor.cif(cif.model.sisters.GCSF.apoptosis.GFPn,
                                                  data=tempdata,cause1=2,cause2=2,
                                                  theta.des=theta.des)
summary(cor.sisters.GCSF.apoptosis.GFPn.distance)

rr.sisters.GCSF.apoptosis.GFPn.distance<-rr.cif(cif.model.sisters.GCSF.apoptosis.GFPn,
                                                  data=tempdata,cause1=2,cause2=2,
                                                  theta.des=theta.des)
summary(rr.sisters.GCSF.apoptosis.GFPn.distance)




ind<-(sisters$Growth_Factor==1)
tempdata<-sisters[ind,]
cif.model.sisters.GCSF.apoptosis.GFPp<-comp.risk(Surv(Event_Time,Cause>0) ~ cluster(PairID),
                                                data=tempdata,cause=tempdata$Status,
                                                causeS=5,resample.iid=1,model="additive",max.clust=10000)
cor.sisters.GCSF.apoptosis.GFPp<-cor.cif(cif.model.sisters.GCSF.apoptosis.GFPp,
                                        data=tempdata,cause1=5,cause2=5)
summary(cor.sisters.GCSF.apoptosis.GFPp)

#regress distance apart

theta.des<-model.matrix(~1+sqrt(tempdata$Diffusion_distance))
cor.sisters.GCSF.apoptosis.GFPp.distance<-cor.cif(cif.model.sisters.GCSF.apoptosis.GFPp,
                                                  data=tempdata,cause1=5,cause2=5,
                                                  theta.des=theta.des)
summary(cor.sisters.GCSF.apoptosis.GFPp.distance)

rr.sisters.GCSF.apoptosis.GFPp.distance<-rr.cif(cif.model.sisters.GCSF.apoptosis.GFPp,
                                                  data=tempdata,cause1=5,cause2=5,
                                                  theta.des=theta.des)
summary(rr.sisters.GCSF.apoptosis.GFPp.distance)


# M-CSF

ind<-(sisters$Growth_Factor==2)
tempdata<-sisters[ind,]
cif.model.sisters.MCSF.apoptosis.GFPn<-comp.risk(Surv(Event_Time,Cause>0) ~ cluster(PairID),
                                                data=tempdata,cause=tempdata$Status,
                                                causeS=2,resample.iid=1,model="additive",max.clust=10000)
cor.sisters.MCSF.apoptosis.GFPn<-cor.cif(cif.model.sisters.MCSF.apoptosis.GFPn,
                                        data=tempdata,cause1=2,cause2=2)
summary(cor.sisters.MCSF.apoptosis.GFPn)

#regress distance appart

theta.des<-model.matrix(~1+sqrt(tempdata$Diffusion_distance))
cor.sisters.MCSF.apoptosis.GFPn.distance<-cor.cif(cif.model.sisters.MCSF.apoptosis.GFPn,
                                         data=tempdata,cause1=2,cause2=2,theta.des=theta.des)
summary(cor.sisters.MCSF.apoptosis.GFPn.distance)
rr.sisters.MCSF.apoptosis.GFPn.distance<-rr.cif(cif.model.sisters.MCSF.apoptosis.GFPn,
                                                  data=tempdata,cause1=2,cause2=2,theta.des=theta.des)
summary(rr.sisters.MCSF.apoptosis.GFPn.distance)



ind<-(sisters$Growth_Factor==2)
tempdata<-sisters[ind,]
cif.model.sisters.MCSF.apoptosis.GFPp<-comp.risk(Surv(Event_Time,Cause>0) ~ cluster(PairID),
                                                data=tempdata,cause=tempdata$Status,
                                                causeS=5,resample.iid=1,model="additive",max.clust=10000)
cor.sisters.MCSF.apoptosis.GFPp<-cor.cif(cif.model.sisters.MCSF.apoptosis.GFPp,
                                        data=tempdata,cause1=5,cause2=5)
summary(cor.sisters.MCSF.apoptosis.GFPp)

#regress distance appart
theta.des<-model.matrix(~1+sqrt(tempdata$Diffusion_distance))
cor.sisters.MCSF.apoptosis.GFPp.distance<-cor.cif(cif.model.sisters.MCSF.apoptosis.GFPp,
                                                  data=tempdata,cause1=5,cause2=5,theta.des=theta.des)
summary(cor.sisters.MCSF.apoptosis.GFPp.distance)

rr.sisters.MCSF.apoptosis.GFPp.distance<-rr.cif(cif.model.sisters.MCSF.apoptosis.GFPp,
                                                  data=tempdata,cause1=5,cause2=5,theta.des=theta.des)
summary(rr.sisters.MCSF.apoptosis.GFPp.distance)
# plot apoptosis concordance for daughters --------------------------------

par(mfcol=c(2,2))
marg.cif1<-predict(cif.model.sisters.GCSF.apoptosis.GFPn,X=1)
ProbandwisePlot(cor.sisters.GCSF.apoptosis.GFPn,marg.cif1=marg.cif1,
                marg.cif2=marg.cif1,title="GCSF GFP- death age",eventtxt1="Sib1",eventtxt2="Sib2")
marg.cif1<-predict(cif.model.sisters.GCSF.apoptosis.GFPp,X=1)
ProbandwisePlot(cor.sisters.GCSF.apoptosis.GFPp,marg.cif1=marg.cif1,
                marg.cif2=marg.cif1,title="GCSF GFP+ death age",eventtxt1="Sib1",eventtxt2="Sib2")
marg.cif1<-predict(cif.model.sisters.MCSF.apoptosis.GFPn,X=1)
ProbandwisePlot(cor.sisters.MCSF.apoptosis.GFPn,marg.cif1=marg.cif1,
                marg.cif2=marg.cif1,title="MCSF GFP- death age",eventtxt1="Sib1",eventtxt2="Sib2")
marg.cif1<-predict(cif.model.sisters.MCSF.apoptosis.GFPp,X=1)
ProbandwisePlot(cor.sisters.MCSF.apoptosis.GFPp,marg.cif1=marg.cif1,
                marg.cif2=marg.cif1,title="MCSF GFP- death age",eventtxt1="Sib1",eventtxt2="Sib2")

# General regression model ---------------------------------------------
FileName<-"K:/James/R/Analysis in R/GMPregression.txt"
data<-read.table(FileName)
# This file is generated by GMP_analysis_script_4R.m
ndx<-data$Generation>0 # only consider generation 1 or greater
tempdata<-data[ndx,]
tempdata$Cause[tempdata$Cause==3]<-0 #lost cell is right censored
tempdata$MCSF<-tempdata$Growth_Factor=="mcsf"
times<-seq(from=0.001,to=3.5,by=0.03)
cif.model.division<-comp.risk(Surv(Event_Time,tempdata$Cause>0)~1+GFP+MCSF:GFP,
                             data=tempdata,times=times,cause=tempdata$Cause,causeS=1,resample.iid=1,model="fg")
summary(cif.model.division) # effect of const(MCSF) was not significant

# plot division
cif.division.MCSF.GFPneg<-predict(cif.model.division,X=c(1,0,0))
cif.division.GCSF.GFPneg<-predict(cif.model.division,X=c(1,0,0))
cif.division.MCSF.GFPpos<-predict(cif.model.division,X=c(1,1,1))
cif.division.GCSF.GFPpos<-predict(cif.model.division,X=c(1,1,0))
par(mfcol=c(1,2))
plot(cif.division.MCSF.GFPneg$time,cif.division.MCSF.GFPneg$P1,type="s",xlab="time to division (days)",ylab="cumulative incidence",
     ylim=c(0,1),xlim=c(0,3),lty=1,lwd=2,col="black",main="Generation>0")
lines(cif.division.MCSF.GFPneg$time,cif.division.MCSF.GFPneg$P1+cif.division.MCSF.GFPneg$se.P1,type="s",lty=2,lwd=2,col="black")
lines(cif.division.MCSF.GFPneg$time,cif.division.MCSF.GFPneg$P1-cif.division.MCSF.GFPneg$se.P1,type="s",lty=2,lwd=2,col="black")
lines(cif.division.MCSF.GFPpos$time,cif.division.MCSF.GFPpos$P1,type="s",lty=1,lwd=2,col="Green")
lines(cif.division.MCSF.GFPpos$time,cif.division.MCSF.GFPpos$P1-cif.division.MCSF.GFPpos$se.P1,type="s",lty=2,lwd=2,col="Green")
lines(cif.division.MCSF.GFPpos$time,cif.division.MCSF.GFPpos$P1+cif.division.MCSF.GFPpos$se.P1,type="s",lty=2,lwd=2,col="Green")
lines(cif.division.GCSF.GFPpos$time,cif.division.GCSF.GFPpos$P1,type="s",lty=1,lwd=2,col="Red")
lines(cif.division.GCSF.GFPpos$time,cif.division.GCSF.GFPpos$P1+cif.division.GCSF.GFPpos$se.P1,type="s",lty=2,lwd=2,col="Red")
lines(cif.division.GCSF.GFPpos$time,cif.division.GCSF.GFPpos$P1-cif.division.GCSF.GFPpos$se.P1,type="s",lty=2,lwd=2,col="Red")
# lines(cif.division.GCSF.GFPneg$time,cif.division.GCSF.GFPneg$P1,type="s",lty=1,lwd=2,col="SlateGray")
# lines(cif.division.GCSF.GFPpos$time,cif.division.GCSF.GFPneg$P1+cif.division.GCSF.GFPneg$se.P1,type="s",lty=2,lwd=2,col="SlateGray")
# lines(cif.division.GCSF.GFPpos$time,cif.division.GCSF.GFPneg$P1-cif.division.GCSF.GFPneg$se.P1,type="s",lty=2,lwd=2,col="SlateGray")
legend(1,0.4,legend=c("GFP-","SE","MCSF,GFP+","GCSF,GFP+"),col=c("black","Black","Green","Red"),
       lwd=c(2,2,2,2),lty=c(1,2,1,1),bty="n")

#death
cif.model.death<-comp.risk(Surv(Event_Time,tempdata$Cause>0)~1+GFP+MCSF:GFP,
                              data=tempdata,times=times,cause=tempdata$Cause,causeS=2,resample.iid=1,model="fg")
summary(cif.model.death)
# plot death
cif.death.MCSF.GFPneg<-predict(cif.model.death,X=c(1,0,0))
cif.death.GCSF.GFPneg<-predict(cif.model.death,X=c(1,0,0))
cif.death.MCSF.GFPpos<-predict(cif.model.death,X=c(1,1,1))
cif.death.GCSF.GFPpos<-predict(cif.model.death,X=c(1,1,0))

plot(cif.death.MCSF.GFPneg$time,cif.death.MCSF.GFPneg$P1,type="s",xlab="time to death (days)",ylab="cumulative incidence",
     ylim=c(0,1),xlim=c(0,3),lty=1,lwd=2,col="black",main="Generation>0")
lines(cif.death.MCSF.GFPneg$time,cif.death.MCSF.GFPneg$P1+cif.death.MCSF.GFPneg$se.P1,type="s",lty=2,lwd=2,col="black")
lines(cif.death.MCSF.GFPneg$time,cif.death.MCSF.GFPneg$P1-cif.death.MCSF.GFPneg$se.P1,type="s",lty=2,lwd=2,col="black")
lines(cif.death.MCSF.GFPpos$time,cif.death.MCSF.GFPpos$P1,type="s",lty=1,lwd=2,col="Green")
lines(cif.death.MCSF.GFPpos$time,cif.death.MCSF.GFPpos$P1-cif.death.MCSF.GFPpos$se.P1,type="s",lty=2,lwd=2,col="Green")
lines(cif.death.MCSF.GFPpos$time,cif.death.MCSF.GFPpos$P1+cif.death.MCSF.GFPpos$se.P1,type="s",lty=2,lwd=2,col="Green")
lines(cif.death.GCSF.GFPpos$time,cif.death.GCSF.GFPpos$P1,type="s",lty=1,lwd=2,col="Red")
lines(cif.death.GCSF.GFPpos$time,cif.death.GCSF.GFPpos$P1+cif.death.GCSF.GFPpos$se.P1,type="s",lty=2,lwd=2,col="Red")
lines(cif.death.GCSF.GFPpos$time,cif.death.GCSF.GFPpos$P1-cif.death.GCSF.GFPpos$se.P1,type="s",lty=2,lwd=2,col="Red")
# lines(cif.death.GCSF.GFPneg$time,cif.death.GCSF.GFPneg$P1,type="s",lty=1,lwd=2,col="SlateGray")
# lines(cif.death.GCSF.GFPpos$time,cif.death.GCSF.GFPneg$P1+cif.death.GCSF.GFPneg$se.P1,type="s",lty=2,lwd=2,col="SlateGray")
# lines(cif.death.GCSF.GFPpos$time,cif.death.GCSF.GFPneg$P1-cif.death.GCSF.GFPneg$se.P1,type="s",lty=2,lwd=2,col="SlateGray")
legend(0,1,legend=c("GFP-","SE","MCSF,GFP+","GCSF,GFP+"),col=c("black","Black","Green","Red"),
       lwd=c(2,2,2,2),lty=c(1,2,1,1),bty="n")

# Concordance analysis -----------------------------
# Get First Generation
# Once again define StatusOfGFP as 0 - censored, 1 - division, 2 - death, 3 GFP onset

# Refresh data
FileName<-"H:\\CellRxLabDoc\\Papers\\My draft papers\\Competing Risks\\James version\\GMP\\GMPDivisionCrossOdds.txt"
data<-read.table(FileName)
# Create GFP_EventTime
# Competes with division and death
data[data$Cause==3,]$Cause<-0 # lost cell is right censored
GFP_Event_Age<-data$Event_Time
GFP_Event_Time<-data$Event_Time+data$BirthAge # BirthAge is really the time from birth of the founding cells to the birth of the current cell
ndx<-is.nan(data$GFP_Age)
GFP_Event_Age[!ndx]<-data$GFP_Age[!ndx]
GFP_Event_Time[!ndx]<-data$GFP_Age[!ndx]+data$BirthAge[!ndx]
GFP_Cause<-data$Cause
GFP_Cause[!ndx]<-3 # GFP on is 3
data$GFP_Cause<-GFP_Cause
data$GFP_Event_Age<-GFP_Event_Age
data$GFP_Event_Time<-GFP_Event_Time


# Relatedness definitions (k+1)/(i+1) where the cousin is defined as the  ith cousin kth removed
#   k  				
# i	0           1       2       3       4       5
# 0	1           2       3       4       5       6
# 1	0.3333     1.5     2.5     3.5     4.5     5.5
# 2	0.25      1.3333  2.3333  3.3333  4.3333  5.3333
# 3	0.2	      1.25	2.25	3.25	4.25	5.25
# 4	0.1667     1.2     2.2     3.2     4.2     5.2

# if cousins are in the same generation then k=0
# mothers and daughters relatedness=2
# sisters are 0th cousins i.e. relatedness=1

MothersAndDaughters=data[data$Relatedness==2,]
tempMAD<-MothersAndDaughters
# need to remove duplicated cells for independent sampling atleast
# MothersAndDaughtersSamp=SampleClones(MothersAndDaughters)
MothersAndDaughters$Mothers<-getMothers(MothersAndDaughters)
write.table(MothersAndDaughters,"H:\\CellRxLabDoc\\Papers\\My draft papers\\Competing Risks\\James version\\GMP\\MothersAndDaughters.txt",sep="\t")
# first cousins are 1/3, second cousins are 1/4, third cousins are 1/5, fourth cousins are 1/6
is.Sister<-abs(data$Relatedness-1)<1e-5
Sisters<-data[is.Sister,]
write.table(Sisters,"H:\\CellRxLabDoc\\Papers\\My draft papers\\Competing Risks\\James version\\GMP\\Sisters.txt",sep="\t")
is.FirstCousin<-abs(data$Relatedness-1/3)<1e-5
FirstCousins<-data[is.FirstCousin,]
# FirstCousins<-SampleClones(FirstCousins)
write.table(FirstCousins,"H:\\CellRxLabDoc\\Papers\\My draft papers\\Competing Risks\\James version\\GMP\\FirstCousins.txt",sep="\t")
is.SecondCousin<-abs(data$Relatednes-1/4)<1e-5
SecondCousins<-data[is.SecondCousin,]
# SecondCousins<-SampleClones(SecondCousins)
write.table(SecondCousins,"H:\\CellRxLabDoc\\Papers\\My draft papers\\Competing Risks\\James version\\GMP\\SecondCousins.txt",sep="\t")
is.ThirdCousin<-abs(data$Relatedness-1/5)<1e-5
ThirdCousins<-data[is.ThirdCousin,]
# ThirdCousins<-SampleClones(ThirdCousins)
write.table(ThirdCousins,"H:\\CellRxLabDoc\\Papers\\My draft papers\\Competing Risks\\James version\\GMP\\ThirdCousins.txt",sep="\t")
is.FourthCousin<-abs(data$Relatedness-1/6)<1e-5
FourthCousins<-data[is.FourthCousin,]
# FourthCousins<-SampleClones(FourthCousins)
write.table(FourthCousins,"H:\\CellRxLabDoc\\Papers\\My draft papers\\Competing Risks\\James version\\GMP\\FourthCousins.txt",sep="\t")
# Concordance between sisters ---------------------------------------
Sisters <- read.delim("H:/CellRxLabDoc/Papers/My draft papers/Competing Risks/James version/GMP/Sisters.txt")
# only analyse pairs with and GFP transition
ndx<-!is.na(Sisters$GFP_Age)# identify PairIDs with GFP transition
PairIDs<-Sisters$PairID[ndx]
for(i in 1:length(ndx)) {
  test<-sum(Sisters$PairID[i]==PairIDs)>0
  if(test) ndx[i]=TRUE
}
tempdata<-Sisters[ndx,]
Sisters.GFPon.Pairs<-getpairs(tempdata,"GFP_Event_Time","GFP_Cause",3)
# add GFP_Cause and GFP_Event_Time to tempdata
cif.model.Sisters.GFPon<-comp.risk(Surv(tempdata$GFP_Event_Time,tempdata$GFP_Cause>0)~1+tempdata$Growth_Factor+cluster(tempdata$PairID),
                           data=tempdata,cause=tempdata$GFP_Cause,causeS=3,
                           resample.iid=1,model="additive",max.clust=1000000)
summary(cif.model.Sisters.GFPon)
cor.Sisters.GFPon<-cor.cif(cif.model.Sisters.GFPon,sym=1,
                           data=tempdata,cause1=3,cause2=3)
summary(cor.Sisters.GFPon)

ndx<-!Sisters$GFP
tempdata<-Sisters[ndx,]
Sisters.Division.Pairs<-getpairs(tempdata,"Event_Time","Cause",1)
cif.model.Sisters.Division<-comp.risk(Surv(tempdata$Event_Time,Cause>0)~1+const(tempdata$Growth_Factor)+cluster(tempdata$PairID),
                              data=tempdata,cause=tempdata$Cause,causeS=1,
                              resample.iid=1,model="fg",max.clust=1000000)
summary(cif.model.Sisters.Division)
cor.Sisters.Division<-cor.cif(cif.model.Sisters.Division,sym=1,
                              data=tempdata,cause1=1,cause2=1)
summary(cor.Sisters.Division)
# GFP positive cells
ndx<-(Sisters$GFP==1)&(Sisters$Growth_Factor==2)
tempdata<-Sisters[ndx,]
Sisters.GFP.Division.Pairs<-getpairs(tempdata,"Event_Time","Cause",1)
cif.model.Sisters.GFP.Division<-comp.risk(Surv(tempdata$Event_Time,Cause>0)~1+cluster(tempdata$PairID),
                                      data=tempdata,cause=tempdata$Cause,causeS=1,
                                      resample.iid=1,model="fg",max.clust=1000000)
summary(cif.model.Sisters.GFP.Division)
cor.Sisters.GFP.Division<-cor.cif(cif.model.Sisters.GFP.Division,sym=1,
                              data=tempdata,cause1=1,cause2=1)
summary(cor.Sisters.GFP.Division)
# Analysis of mother and daughters   --------------------------------------
MothersAndDaughters <- read.delim("H:/CellRxLabDoc/Papers/My draft papers/Competing Risks/James version/GMP/MothersAndDaughters.txt")
# don't resample
# MothersAndDaughters=data[data$Relatedness==2,]
ndx<-!is.nan(MothersAndDaughters$GFP_Age)# identify PairIDs with GFP transition
PairIDs<-MothersAndDaughters$PairID[ndx]
for(i in 1:length(ndx)) {
  test<-sum(MothersAndDaughters$PairID[i]==PairIDs)>0
  if(test) ndx[i]=TRUE
}
tempdata<-MothersAndDaughters[ndx,]
MotherAndDaughter.GFPon.Pairs<-getpairs(tempdata,"GFP_Event_Time","GFP_Cause",3)
cif.model.MothersAndDaughters.GFPon<-comp.risk(Surv(tempdata$GFP_Event_Time,GFP_Cause>0)~1+Growth_Factor+cluster(tempdata$PairID),
                           data=tempdata,cause=tempdata$GFP_Cause,causeS=3,
                           resample.iid=1,model="additive",max.clust=10000)
summary(cif.model.MothersAndDaughters.GFPon)
cor.MothersAndDaughters.GFPon<-cor.cif(cif.model.MothersAndDaughters.GFPon,sym=1,
                           data=tempdata,cause1=3,cause2=3)
summary(cor.MothersAndDaughters.GFPon)

ndx<-(!MothersAndDaughters$GFP)&(MothersAndDaughters$Generation>0) # exclude generation 0
tempdata<-MothersAndDaughters[ndx,]
MotherAndDaughter.Division.Pairs<-getMotherAndDaughterpairs(tempdata,"Event_Time","Cause",1)
cif.model.MothersAndDaughters.Division<-comp.risk(Surv(tempdata$Event_Time,Cause>0)~1+tempdata$Growth_Factor+cluster(tempdata$PairID),
                              data=tempdata,cause=tempdata$Cause,causeS=1,
                              resample.iid=1,model="fg",max.clust=1000000)
summary(cif.model.MothersAndDaughters.Division)
cor.MothersAndDaughters.Division<-cor.cif(cif.model.MothersAndDaughters.Division,sym=1,
                              data=tempdata,cause1=1,cause2=1)
summary(cor.MothersAndDaughters.Division)

# GFP positive
ndx<-(MothersAndDaughters$GFP==1)&(MothersAndDaughters$Generation>0)&(MothersAndDaughters$Growth_Factor==2) # exclude generation 0, MSCF only
tempdata<-MothersAndDaughters[ndx,]
MotherAndDaughter.GFP.Division.Pairs<-getMotherAndDaughterpairs(tempdata,"Event_Time","Cause",1)
cif.model.MothersAndDaughters.GFP.Division<-comp.risk(Surv(tempdata$Event_Time,Cause>0)~1+cluster(tempdata$PairID),
                                                  data=tempdata,cause=tempdata$Cause,causeS=1,
                                                  resample.iid=1,model="fg",max.clust=1000000)
summary(cif.model.MothersAndDaughters.GFP.Division)
cor.MothersAndDaughters.GFP.Division<-cor.cif(cif.model.MothersAndDaughters.GFP.Division,sym=1,
                                          data=tempdata,cause1=1,cause2=1)
summary(cor.MothersAndDaughters.GFP.Division)
# Concordance between 1st cousins ---------------------------------------
FirstCousins <- read.delim("H:/CellRxLabDoc/Papers/My draft papers/Competing Risks/James version/GMP/FirstCousins.txt") # sampled without replacement
# don't sample without replacement
# is.FirstCousin<-abs(data$Relatedness-1/3)<1e-5
# FirstCousins<-data[is.FirstCousin,]
ndx<-!is.nan(FirstCousins$GFP_Age)# identify PairIDs with GFP transition
for(i in 1:length(ndx)) {
  test<-sum(FirstCousins$PairID[i]==PairIDs)>0
  if(test) ndx[i]=TRUE
}


tempdata<-FirstCousins[ndx,]
FirstCousins.GFPon.Pairs<-getpairs(tempdata,"GFP_Event_Time","GFP_Cause",3)

cif.model.FirstCousins.GFPon<-comp.risk(Surv(tempdata$GFP_Event_Time,tempdata$GFP_Cause>0)~+1+cluster(tempdata$PairID),
                           data=tempdata,cause=tempdata$GFP_Cause,causeS=3,
                           resample.iid=1,model="additive",max.clust=200000)
summary(cif.model.FirstCousins.GFPon)
cor.FirstCousins.GFPon<-cor.cif(cif.model.FirstCousins.GFPon,
                                data=tempdata,cause1=3,cause2=3,sym=1)
summary(cor.FirstCousins.GFPon)



ndx<-!FirstCousins$GFP
tempdata<-FirstCousins[ndx,]
FirstCousins.Division.Pairs<-getpairs(tempdata,"Event_Time","Cause",1)
cif.model.FirstCousins.Division<-comp.risk(Surv(tempdata$Event_Time,Cause>0)~1+const(Growth_Factor)+cluster(PairID),
                              data=tempdata,cause=tempdata$Cause,causeS=1,
                              resample.iid=1,model="fg",max.clust=1000000)
summary(cif.model.FirstCousins.Division)
cor.FirstCousins.Division<-cor.cif(cif.model.FirstCousins.Division,sym=1,
                                   data=tempdata,cause1=1,cause2=1)
summary(cor.FirstCousins.Division)

# GFP positive
ndx<-(FirstCousins$GFP==1)&(FirstCousins$Growth_Factor==2)
tempdata<-FirstCousins[ndx,]
FirstCousins.GFP.Division.Pairs<-getpairs(tempdata,"Event_Time","Cause",1)
cif.model.FirstCousins.GFP.Division<-comp.risk(Surv(tempdata$Event_Time,Cause>0)~1+cluster(PairID),
                                           data=tempdata,cause=tempdata$Cause,causeS=1,
                                           resample.iid=1,model="fg",max.clust=1000000)
summary(cif.model.FirstCousins.GFP.Division)
cor.FirstCousins.GFP.Division<-cor.cif(cif.model.FirstCousins.GFP.Division,sym=1,
                                   data=tempdata,cause1=1,cause2=1)
summary(cor.FirstCousins.GFP.Division)
# Concordance between 2nd cousins ---------------------------------------
SecondCousins <- read.delim("H:/CellRxLabDoc/Papers/My draft papers/Competing Risks/James version/GMP/SecondCousins.txt")
# don't sample without replacement
# is.SecondCousin<-abs(data$Relatedness-1/4)<1e-5
# SecondCousins<-data[is.SecondCousin,]
ndx<-!is.nan(SecondCousins$GFP_Age)# identify PairIDs with GFP transition
for(i in 1:length(ndx)) {
  test<-sum(SecondCousins$PairID[i]==PairIDs)>0
  if(test) ndx[i]=TRUE
}
tempdata<-SecondCousins[ndx,]
SecondCousins.GFPon.Pairs<-getpairs(tempdata,"GFP_Event_Time","GFP_Cause",3)
cif.model.SecondCousins.GFPon<-comp.risk(Surv(tempdata$GFP_Event_Time,GFP_Cause>0)~1+cluster(PairID),
                           data=tempdata,cause=tempdata$GFP_Cause,causeS=3,
                           resample.iid=1,model="additive",max.clust=1000000)
summary(cif.model.SecondCousins.GFPon)
cor.SecondCousins.GFPon<-cor.cif(cif.model.SecondCousins.GFPon,sym=1,
                                 data=tempdata,cause1=3,cause2=3)
summary(cor.SecondCousins.GFPon)

ndx<-!SecondCousins$GFP
tempdata<-SecondCousins[ndx,]
SecondCousins.Division.Pairs<-getpairs(tempdata,"Event_Time","Cause",1)
cif.model.SecondCousins.Division<-comp.risk(Surv(tempdata$Event_Time,Cause>0)~1+const(Growth_Factor)+cluster(PairID),
                              data=tempdata,cause=tempdata$Cause,causeS=1,
                              resample.iid=1,model="fg",max.clust=1000000)
summary(cif.model.SecondCousins.Division)
cor.SecondCousins.Division<-cor.cif(cif.model.SecondCousins.Division,sym=1,
                                    data=tempdata,cause1=1,cause2=1)
summary(cor.SecondCousins.Division)

# GFP positive
ndx<-(SecondCousins$GFP==1)&(SecondCousins$Growth_Factor==2)
tempdata<-SecondCousins[ndx,]
SecondCousins.GFP.Division.Pairs<-getpairs(tempdata,"Event_Time","Cause",1)
cif.model.SecondCousins.GFP.Division<-comp.risk(Surv(tempdata$Event_Time,Cause>0)~1+cluster(PairID),
                                            data=tempdata,cause=tempdata$Cause,causeS=1,
                                            resample.iid=1,model="fg",max.clust=1000000)
summary(cif.model.SecondCousins.GFP.Division)
cor.SecondCousins.GFP.Division<-cor.cif(cif.model.SecondCousins.GFP.Division,sym=1,
                                    data=tempdata,cause1=1,cause2=1)
summary(cor.SecondCousins.GFP.Division)
# Concordance between 3rd cousins ---------------------------------------
ThirdCousins <- read.delim("H:/CellRxLabDoc/Papers/My draft papers/Competing Risks/James version/GMP/ThirdCousins.txt")
# don't sample without replacement
is.ThirdCousin<-abs(data$Relatedness-1/5)<1e-5
ThirdCousins<-data[is.ThirdCousin,]
ndx<-!is.nan(ThirdCousins$GFP_Age)# identify PairIDs with GFP transition
for(i in 1:length(ndx)) {
  test<-sum(ThirdCousins$PairID[i]==PairIDs)>0
  if(test) ndx[i]=TRUE
}
tempdata<-ThirdCousins[ndx,]
ThirdCousins.GFPon.Pairs<-getpairs(tempdata,"GFP_Event_Time","GFP_Cause",3)
cif.model.ThirdCousins.GFPon<-comp.risk(Surv(tempdata$GFP_Event_Time,GFP_Cause>0)~1+const(Growth_Factor)+cluster(PairID),
                           data=tempdata,cause=tempdata$GFP_Cause,causeS=3,
                           resample.iid=1,model="additive",max.clust=1000000)
summary(cif.model.ThirdCousins.GFPon)
cor.ThirdCousins.GFPon<-cor.cif(cif.model.ThirdCousins.GFPon,sym=1,
                                data=tempdata,cause1=3,cause2=3)
summary(cor.ThirdCousins.GFPon)

ndx<-!ThirdCousins$GFP 
tempdata<-ThirdCousins[ndx,]
ThirdCousins.Division.Pairs<-getpairs(tempdata,"Event_Time","Cause",1)
cif.model.ThirdCousins.Division<-comp.risk(Surv(tempdata$Event_Time,Cause>0)~1+const(Growth_Factor)+cluster(PairID),
                              data=tempdata,cause=tempdata$Cause,causeS=1,
                              resample.iid=1,model="fg",max.clust=1000000)
summary(cif.model.ThirdCousins.Division)
cor.ThirdCousins.Division<-cor.cif(cif.model.ThirdCousins.Division,sym=1,
                                   data=tempdata,cause1=1,cause2=1)
summary(cor.ThirdCousins.Division)
# GFP positive
ndx<-(ThirdCousins$GFP==1)&(ThirdCousins$Growth_Factor==2)
tempdata<-ThirdCousins[ndx,]
ThirdCousins.GFP.Division.Pairs<-getpairs(tempdata,"Event_Time","Cause",1)
cif.model.ThirdCousins.GFP.Division<-comp.risk(Surv(tempdata$Event_Time,Cause>0)~1+cluster(PairID),
                                           data=tempdata,cause=tempdata$Cause,causeS=1,
                                           resample.iid=1,model="fg",max.clust=1000000)
summary(cif.model.ThirdCousins.GFP.Division)
cor.ThirdCousins.GFP.Division<-cor.cif(cif.model.ThirdCousins.GFP.Division,sym=1,
                                   data=tempdata,cause1=1,cause2=1)
summary(cor.ThirdCousins.GFP.Division)
# Bivariate dotplots between relatives ------------------------------------
# GFP on
par(mfrow=c(3,1))
s<-cor.test(Sisters.GFPon.Pairs[,1],Sisters.GFPon.Pairs[,2],method="pearson")
plot(Sisters.GFPon.Pairs,xlab="sib1 GFP on (days)",ylab="sib2 GFP on (days)",pch=20,main="Sisters",
     sub=paste("rho=",format(s$estimate,digits=3),", p=",s$p.value))
m<-max(Sisters.GFPon.Pairs)
lines(c(0,m),c(0,m))
s<-cor.test(FirstCousins.GFPon.Pairs[,1],FirstCousins.GFPon.Pairs[,2],method="pearson")
plot(FirstCousins.GFPon.Pairs,xlab="cousin 1 GFP on (days)",ylab="cousin 2 GFP on (days)",pch=20,main="First Cousins",
     sub=paste("rho=",format(s$estimate,digits=3),", p=",s$p.value))
m<-max(FirstCousins.GFPon.Pairs)
lines(c(0,m),c(0,m))
s<-cor.test(SecondCousins.GFPon.Pairs[,1],SecondCousins.GFPon.Pairs[,2],method="pearson")
plot(SecondCousins.GFPon.Pairs,xlab="cousin 1 GFP on (days)",ylab="cousin 2 GFP on (days)",pch=20,main="Second Cousins",
     sub=paste("rho=",format(s$estimate,digits=3),", p=",s$p.value))
m<-max(SecondCousins.GFPon.Pairs)
lines(c(0,m),c(0,m))
# plot division times
par(mfrow=c(2,2))
v<-dim(Sisters.Division.Pairs) # randomise sisters
for (i in 1:v[1]) {
  pair<-sample(Sisters.Division.Pairs[i,],2,replace=FALSE)
  Sisters.Division.Pairs[i,]<-pair
}
s<-cor.test(Sisters.Division.Pairs[,1],Sisters.Division.Pairs[,2],method="pearson")
plot(Sisters.Division.Pairs,xlab="sib1 division age (days)",ylab="sib2 division age (days)",pch=20,main="Sisters",
     sub=paste("rho=",format(s$estimate,digits=3),", p=",s$p.value))
m<-max(Sisters.Division.Pairs)
lines(c(0,m),c(0,m))
# mothers and daughters
s<-cor.test(MotherAndDaughter.Division.Pairs[,1],MotherAndDaughter.Division.Pairs[,2],pch=20,method="pearson")
plot(MotherAndDaughter.Division.Pairs,xlab="child division age (days)",ylab="parent division age (days)",pch=20,main="Parent-Child division age",
     sub=paste("rho=",format(s$estimate,digits=3),", p=",s$p.value))
m<-max(MotherAndDaughter.Division.Pairs)
lines(c(0,m),c(0,m))
# first cousin
v<-dim(FirstCousins.Division.Pairs) # randomise sisters
for (i in 1:v[1]) {
  pair<-sample(FirstCousins.Division.Pairs[i,],2,replace=FALSE)
  FirstCousins.Division.Pairs[i,]<-pair
}
s<-cor.test(FirstCousins.Division.Pairs[,1],FirstCousins.Division.Pairs[,2],method="pearson")
plot(FirstCousins.Division.Pairs,xlab="cousin 1 division age (days)",ylab="cousin 2 division age (days)",pch=20,main="First Cousins",
     sub=paste("rho=",format(s$estimate,digits=3),", p=",s$p.value))
m<-max(FirstCousins.Division.Pairs)
lines(c(0,m),c(0,m))
#second cousins
v<-dim(SecondCousins.Division.Pairs) # randomise sisters
for (i in 1:v[1]) {
  pair<-sample(SecondCousins.Division.Pairs[i,],2,replace=FALSE)
  SecondCousins.Division.Pairs[i,]<-pair
}
s<-cor.test(SecondCousins.Division.Pairs[,1],SecondCousins.Division.Pairs[,2],method="pearson")
plot(SecondCousins.Division.Pairs,xlab="cousin 1 division age (days)",ylab="cousin 2 division age (days)",pch=20,main="Second Cousins",
     sub=paste("rho=",format(s$estimate,digits=3),", p=",s$p.value))
m<-max(SecondCousins.Division.Pairs)
lines(c(0,m),c(0,m))

# plot division times for GFP positive cells
par(mfrow=c(2,2))
v<-dim(Sisters.GFP.Division.Pairs) # randomise sisters
for (i in 1:v[1]) {
  pair<-sample(Sisters.GFP.Division.Pairs[i,],2,replace=FALSE)
  Sisters.GFP.Division.Pairs[i,]<-pair
}
s<-cor.test(Sisters.GFP.Division.Pairs[,1],Sisters.GFP.Division.Pairs[,2],method="pearson")
plot(Sisters.GFP.Division.Pairs,xlab="sib1 division age (days)",ylab="sib2 division age (days)",pch=20,main="Sisters",
     sub=paste("rho=",format(s$estimate,digits=3),", p=",s$p.value))
m<-max(Sisters.GFP.Division.Pairs)
lines(c(0,m),c(0,m))
# mothers and daughters
s<-cor.test(MotherAndDaughter.GFP.Division.Pairs[,1],MotherAndDaughter.GFP.Division.Pairs[,2],method="pearson")
plot(MotherAndDaughter.GFP.Division.Pairs,xlab="child division age (days)",ylab="parent division age (days)",pch=20,main="Parent-Child division age",
     sub=paste("rho=",format(s$estimate,digits=3),", p=",s$p.value))
m<-max(MotherAndDaughter.GFP.Division.Pairs)
lines(c(0,m),c(0,m))
# first cousin
v<-dim(FirstCousins.GFP.Division.Pairs) # randomise sisters
for (i in 1:v[1]) {
  pair<-sample(FirstCousins.GFP.Division.Pairs[i,],2,replace=FALSE)
  FirstCousins.GFP.Division.Pairs[i,]<-pair
}
s<-cor.test(FirstCousins.GFP.Division.Pairs[,1],FirstCousins.GFP.Division.Pairs[,2],method="pearson")
plot(FirstCousins.GFP.Division.Pairs,xlab="cousin 1 division age (days)",ylab="cousin 2 division age (days)",pch=20,main="First Cousins",
     sub=paste("rho=",format(s$estimate,digits=3),", p=",s$p.value))
m<-max(FirstCousins.GFP.Division.Pairs)
lines(c(0,m),c(0,m))
#second cousins
v<-dim(SecondCousins.GFP.Division.Pairs) # randomise sisters
for (i in 1:v[1]) {
  pair<-sample(SecondCousins.GFP.Division.Pairs[i,],2,replace=FALSE)
  SecondCousins.GFP.Division.Pairs[i,]<-pair
}
s<-cor.test(SecondCousins.GFP.Division.Pairs[,1],SecondCousins.GFP.Division.Pairs[,2],method="pearson")
plot(SecondCousins.GFP.Division.Pairs,xlab="cousin 1 division age (days)",ylab="cousin 2 division age (days)",pch=20,main="Second Cousins",
     sub=paste("rho=",format(s$estimate,digits=3),", p=",s$p.value))
m<-max(SecondCousins.GFP.Division.Pairs)
lines(c(0,m),c(0,m))

# Ploting relative division concordance --------------------------------------------
par(mfcol=c(2,2))
cif1<-predict(cif.model.Sisters.Division,X=1,Z=2) # MCSF
con<-concordance(cor.Sisters.Division,cif1$P1)
plot(cif1$time,con$intercept$probandwise[,1],type="s",
     sub="Division concordance probability (GFP-)",ylim=c(0,1),lwd=2,xlim=c(0,2),
     xlab="Cell age",ylab="Probability",col="black")
lines(cif1$time,con$intercept$probandwise[,2],type="s",lty=2,col="black")
lines(cif1$time,con$intercept$probandwise[,3],type="s",lty=2,col="black")

cif1<-predict(cif.model.FirstCousins.Division,X=1,Z=2)
con<-concordance(cor.FirstCousins.Division,cif1$P1)
lines(cif1$time,con$intercept$probandwise[,1],type="s",
     lwd=2,col="red")
lines(cif1$time,con$intercept$probandwise[,2],type="s",lty=2,col="red")
lines(cif1$time,con$intercept$probandwise[,3],type="s",lty=2,col="red")

cif1<-predict(cif.model.MothersAndDaughters.Division,X=c(1,2))
con<-concordance(cor.MothersAndDaughters.Division,cif1$P1)
lines(cif1$time,con$intercept$probandwise[,1],type="s",
      lwd=2,col="green")
lines(cif1$time,con$intercept$probandwise[,2],type="s",lty=2,col="green")
lines(cif1$time,con$intercept$probandwise[,3],type="s",lty=2,col="green")

cif1<-predict(cif.model.SecondCousins.Division,X=1,Z=2)
con<-concordance(cor.SecondCousins.Division,cif1$P1)
lines(cif1$time,con$intercept$probandwise[,1],type="s",
      lwd=2,col="blue")
lines(cif1$time,con$intercept$probandwise[,2],type="s",lty=2,col="blue")
lines(cif1$time,con$intercept$probandwise[,3],type="s",lty=2,col="blue")

legend(0.8,1,legend=c("siblings","parent-child","1st cousin","2nd cousin","95% CI"),
       col=c("black","green","red","blue","black"),
       lty=c(1,1,1,1,2),lwd=c(2,2,2,2,1),bty="n")
# GFP positive
cif1<-predict(cif.model.Sisters.GFP.Division,X=1) # MCSF
con<-concordance(cor.Sisters.Division,GFP.cif1$P1)
plot(cif1$time,con$intercept$probandwise[,1],type="s",
     sub="Division concordance probability (GFP+)",ylim=c(0,1),lwd=2,xlim=c(0,2),
     xlab="Cell age",ylab="Probability",col="black")
lines(cif1$time,con$intercept$probandwise[,2],type="s",lty=2,col="black")
lines(cif1$time,con$intercept$probandwise[,3],type="s",lty=2,col="black")

cif1<-predict(cif.model.FirstCousins.GFP.Division,X=1)
con<-concordance(cor.FirstCousins.GFP.Division,cif1$P1)
lines(cif1$time,con$intercept$probandwise[,1],type="s",
      lwd=2,col="red")
lines(cif1$time,con$intercept$probandwise[,2],type="s",lty=2,col="red")
lines(cif1$time,con$intercept$probandwise[,3],type="s",lty=2,col="red")

cif1<-predict(cif.model.MothersAndDaughters.GFP.Division,X=1)
con<-concordance(cor.MothersAndDaughters.GFP.Division,cif1$P1)
lines(cif1$time,con$intercept$probandwise[,1],type="s",
      lwd=2,col="green")
lines(cif1$time,con$intercept$probandwise[,2],type="s",lty=2,col="green")
lines(cif1$time,con$intercept$probandwise[,3],type="s",lty=2,col="green")

cif1<-predict(cif.model.SecondCousins.GFP.Division,X=1)
con<-concordance(cor.SecondCousins.GFP.Division,cif1$P1)
lines(cif1$time,con$intercept$probandwise[,1],type="s",
      lwd=2,col="blue")
lines(cif1$time,con$intercept$probandwise[,2],type="s",lty=2,col="blue")
lines(cif1$time,con$intercept$probandwise[,3],type="s",lty=2,col="blue")

# legend(1.2,0.8,legend=c("siblings","parent-child","1st cousin","2nd cousin","95% CI"),
#        col=c("black","green","red","blue","black"),
#        lty=c(1,1,1,1,2),lwd=c(2,2,2,2,1),bty="n")
# Bar graph showing generational distribution of GFP onset-------------------------------------

ndx<-!is.nan(data$GFP_Age)
GFPTransition<-data$Generation[ndx]
GFPTransitionTable<-table(GFPTransition)
barplot(GFPTransitionTable,names.arg=0:7,xlab="Generation",ylab="Cell number",sub="Onset of GFP fluorescence")
# Ploting relative gfp onset concordance ----------------------------------
cif1<-predict(cif.model.Sisters.GFPon,X=c(1,2)) # MCSF
con<-concordance(cor.Sisters.GFPon,cif1$P1)
plot(cif1$time,con$intercept$probandwise[,1],type="s",
     sub="GFP expression concordance probability",ylim=c(0,1),lwd=2,
     xlab="Time from start of experiment (days)",ylab="Probability",col="black")
lines(cif1$time,con$intercept$probandwise[,2],type="s",lty=2,col="black")
lines(cif1$time,con$intercept$probandwise[,3],type="s",lty=2,col="black")

cif1<-predict(cif.model.FirstCousins.GFPon,X=1)
con<-concordance(cor.FirstCousins.GFPon,cif1$P1)
lines(cif1$time,con$intercept$probandwise[,1],type="s",
      lwd=2,col="red")
lines(cif1$time,con$intercept$probandwise[,2],type="s",lty=2,col="red")
lines(cif1$time,con$intercept$probandwise[,3],type="s",lty=2,col="red")

cif1<-predict(cif.model.SecondCousins.GFPon,X=1)
con<-concordance(cor.SecondCousins.GFPon,cif1$P1)
lines(cif1$time,con$intercept$probandwise[,1],type="s",
      lwd=2,col="blue")
lines(cif1$time,con$intercept$probandwise[,2],type="s",lty=2,col="blue")
lines(cif1$time,con$intercept$probandwise[,3],type="s",lty=2,col="blue")

# cif1<-predict(cif.model.ThirdCousins.GFPon,X=1)
# con<-concordance(cor.ThirdCousins.GFPon,cif1$P1)
# lines(cif1$time,con$intercept$probandwise[,1],type="s",
#       lwd=2,col="chocolate")
# lines(cif1$time,con$intercept$probandwise[,2],type="s",lty=2,col="chocolate")
# lines(cif1$time,con$intercept$probandwise[,3],type="s",lty=2,col="chocolate")

legend(3,0.7,legend=c("siblings","1st cousins","2nd cousins","95% CI"),
       col=c("black","red","blue","black"),
       lty=c(1,1,1,2),lwd=c(2,2,2,1),bty="n")
#compare stats----
Data2<-read.delim("F:/James/R/Analysis in R/GMPDivisionCrossOdds.txt")
data<-Data2
data$CauseNum<-0
data$CauseNum[data$Cause==0]<-0
data$CauseNum[data$Cause==2]<-2
data$CauseNum[data$Cause==3]<-1
data$CauseNum[data$Cause==1]<-1

##frequency of right censoring in data set

#total data set
total_ndx<-unique(data$PairID) #total number of unique pairs 
total<-data[total_ndx,]
#sisters and cousins
# is.FirstCousin<-abs(data$Relatedness-1/3)<1e-5
# cousins<-data[is.FirstCousin,]
is.SecondCousin<-abs(data$Relatednes-1/4)<1e-5
cousins<-data[is.SecondCousin,]
sisters<-cousins
# sisters<-data[data$Relatedness==2,]
uniquepairs<-unique(sisters$PairID)
div_div<-0
death_death<-0
fate_censored<-0
div_death<-0

for(i in 1:length(uniquepairs)){
  pairdata<-sisters[sisters$PairID==uniquepairs[i],]
  
  if (pairdata$CauseNum[1]==1 & pairdata$CauseNum[2]==1) {
    div_div<-div_div+1
    
  }
  else if (pairdata$CauseNum[1]==2 & pairdata$CauseNum[2]==2){
    death_death<-death_death+1
  }
  else if (pairdata$CauseNum[1]==0 | pairdata$CauseNum[2]==0){
    fate_censored<-fate_censored+1
  }
  else if (pairdata$CauseNum[1]!=pairdata$CauseNum[2] & pairdata$CauseNum[1]!=0 & pairdata$CauseNum[2]!=0){
    div_death<-div_death+1
  }
  
}

#compare with other tests of correlation and concordance data

binomial_div_cens<-binom.test(div_div,length(uniquepairs))
binomial_death_cens<-binom.test(death_death,length(uniquepairs))

binomial_div<-binom.test(div_div,(div_div+death_death))
binomial_death<-binom.test(death_death,(div_div+death_death))



